# Generated by Django 5.2.1 on 2025-05-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satisfaction_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaireClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_date', models.DateTimeField()),
                ('id_client', models.IntegerField()),
                ('nps', models.CharField(max_length=255)),
                ('commentaire', models.CharField(max_length=255)),
                ('sentiment', models.CharField(max_length=255)),
                ('theme', models.CharField(max_length=255)),
                ('score_prediction', models.FloatField()),
                ('nps_match', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'commentaire_client',
                'managed': False,
            },
        ),
    ]
