# Generated by Django 5.1.4 on 2025-05-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaireClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_date', models.DateField(null=True, verbose_name='Date du sondage')),
                ('id_client', models.IntegerField(verbose_name='ID Client')),
                ('nps', models.IntegerField(null=True, verbose_name='NPS')),
                ('commentaire', models.TextField(verbose_name='Commentaire')),
                ('sentiment', models.CharField(max_length=20, null=True, verbose_name='Sentiment')),
                ('theme', models.CharField(max_length=50, null=True, verbose_name='Thème')),
                ('confiance', models.FloatField(null=True, verbose_name='Confiance')),
                ('nps_match', models.BooleanField(null=True, verbose_name='Correspondance NPS')),
            ],
        ),
    ]
