# Generated by Django 5.2.1 on 2025-05-24 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Commentaire', '0003_alter_commentaireclient_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commentaireclient',
            table='commentaire_client',
        ),
    ]
